eureka:
  client:
    serviceUrl:
      defaultZone: http://202.115.161.211:17001/eureka/

spring:
  # mysql 配置
  datasource:
    url: jdbc:mysql://202.115.161.211:13307/oj3?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: wzy
    password: wzy
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  # redis 配置
  redis:
    host: 202.115.161.211
    port: 16379
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
